version: "3.8"

services:
  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=
      - JWT_SECRET=
      - JWT_EXPIRATION_MINUTES=
      - SMTP_EMAIL=
      - SMTP_PASSWORD=
      - MAP_API_KEY=
      - TZ=Asia/Dhaka
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; pnpm run db && pnpm run dev'
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_JWT_SECRET=
      - NEXT_PUBLIC_RECAPTCHA_SITE_KEY=
      - RECAPTCHA_SECRET_KEY=
      - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=
      - NEXT_PUBLIC_CLOUDINARY_API_KEY=
      - NEXT_PUBLIC_CLOUDINARY_API_SECRET=
      - NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET=
      - NEXT_PUBLIC_MAP_API_KEY=
      - TZ=Asia/Dhaka
    depends_on:
      - backend
    links:
      - backend
