export const userRole = {
  admin: "admin",
  sts_manager: "sts_manager",
  landfill_manager: "landfill_manager",
  unassigned: "unassigned",
};

export const rolePermissions = {
  CREATE_USER: "CREATE_USER",
  DELETE_USER: "DELETE_USER",
  UPDATE_USER: "UPDATE_USER",
  READ_USER: "READ_USER",
  CREATE_STS: "CREATE_STS",
  UPDATE_STS: "UPDATE_STS",
  DELETE_STS: "DELETE_STS",
  READ_STS: "READ_STS",
  CREATE_LANDFILL: "CREATE_LANDFILL",
  UPDATE_LANDFILL: "UPDATE_LANDFILL",
  DELETE_LANDFILL: "DELETE_LANDFILL",
  READ_LANDFILL: "READ_LANDFILL",
  CREATE_VEHICLE: "CREATE_VEHICLE",
  UPDATE_VEHICLE: "UPDATE_VEHICLE",
  DELETE_VEHICLE: "DELETE_VEHICLE",
  READ_VEHICLE: "READ_VEHICLE",
  READ_PROFILE: "READ_PROFILE",
  UPDATE_PROFILE: "UPDATE_PROFILE",
  STS_VEHICLE_UPDATE: "STS_VEHICLE_UPDATE",
  LANDFILL_VEHICLE_UPDATE: "LANDFILL_VEHICLE_UPDATE",
};
